# SPDX-FileCopyrightText: 2024 OIDC Sweden
#
# SPDX-License-Identifier: Apache-2.0

name: Publish artifact

on:
  workflow_call:
    secrets:
      WORKFLOW_TOKEN:
        required: true

jobs:
  publish-container:
    name: Build and Publish Container Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up JDK 21
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven
          server-id: github
          server-username: ${{ github.repository_owner }}
          server-password: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Show Generated Settings
        run: |
          echo "Maven settings content:"
          cat ~/.m2/settings.xml
          echo "Using token for repository: ${{ github.repository }}"
          echo "Using owner: ${{ github.repository_owner }}"

      - name: Build, Generate SBOM
        run: |
          mvn -B clean package
      - name: Publish Package with Curl
        run: |
          # First publish the POM
          curl -v \
            -X PUT \
            -H "Authorization: Bearer ${{ secrets.WORKFLOW_TOKEN }}" \
            -H "Content-Type: application/xml" \
            --data-binary "@pom.xml" \
            "https://maven.pkg.github.com/danneleaf/oid-fed-base-test/com/github/danneleaf/oid-fed-base-test/2.0.2/oid-fed-base-test-2.0.2.pom"
            
          # Then publish the JAR
          curl -v \
            -X PUT \
            -H "Authorization: Bearer ${{ secrets.WORKFLOW_TOKEN }}" \
            -H "Content-Type: application/java-archive" \
            --data-binary "@target/oid-fed-base-test-2.0.2.jar" \
            "https://maven.pkg.github.com/danneleaf/oid-fed-base-test/com/github/danneleaf/oid-fed-base-test/2.0.2/oid-fed-base-test-2.0.2.jar"

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: target/bom.json