# SPDX-FileCopyrightText: 2024 OIDC Sweden
#
# SPDX-License-Identifier: Apache-2.0

name: Publish artifact 

on: [workflow_call] # yamllint disable-line rule:truthy

jobs:
  publish-container:
    name: Build and Publish Container Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Test Token Access
        run: |
          echo "Testing GitHub API access..."
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: Bearer ${{ secrets.PACKAGES_TOKEN }}" \
            https://api.github.com/danneleaf)
          echo "API Status: $HTTP_STATUS"
      - name: Set up JDK 21
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.PACKAGES_TOKEN }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      
      - name: Build, Generate SBOM, and Deploy
        run: |
          mvn -B clean package cyclonedx:makeAggregateBom
          mvn -B -e deploy
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
      
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: target/bom.json
